name: UCI self-hosted test
on:
  pull_request: 
  workflow_dispatch:
jobs:
  Test:
    runs-on: uci-default
    steps:
      - run: echo "Hello from self-hosted runner"
      - run: uname -a
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: '1.25.6'
      - run: ls -alh
      - run: go build .
